const CATEGORIES = ["대입 · 진학지도", "학교 업무 자동화", "개인 생산성 자동화"];

const PROJECTS = [
  {
    id: "ipsi-db",
    title: "ipsi-db",
    category: "대입 · 진학지도",
    status: "in-progress",
    visibility: "public",
    purpose: "대학 수시·정시 세부전형별 모집인원, 경쟁률, 충원률, '어디가' 발표 기준점수(컷) 등을 종합한 진학지도용 데이터베이스와 대시보드 제작.",
    method: "Python 스크립트로 데이터 수집·정제 후 조회 가능한 형태로 관리.",
    tags: ["Python"],
    repo: "https://github.com/taeyun200/ipsi-db",
    updated: "2026.07.30",
  },
  {
    id: "hapbul",
    title: "대입 결과분석 대시보드",
    category: "대입 · 진학지도",
    status: "done",
    visibility: "private",
    purpose: "지역 대입지원단 소속 여러 고교의 수시 진학관리 데이터를 분석·시각화해 지원 경향과 합불 판정을 확인하는 도구.",
    method: [
      "서버형 대시보드: 원본 데이터는 서버에만 두고 로그인한 학교에는 질의당 집계만 제공(원본 추출 불가)",
      "로컬 오프라인 도구: 학교별 엑셀을 올려 쓰는 단일 HTML(서버 불필요)",
      "두 도구가 선호도 매핑·합불 판정 로직을 공유",
    ],
    tags: ["Python", "HTML/JS", "Cloudflare Workers", "D1"],
    updated: "2026.07.27",
  },
  {
    id: "grade5-position-convert",
    title: "5등급 위치변환",
    category: "대입 · 진학지도",
    status: "done",
    visibility: "private",
    purpose: '9등급제 시절 누적된 대입 결과를 백분위(위치) 축으로 변환하고, 5등급제 학생의 내신을 같은 축으로 환산해 "비슷한 위치의 과거 학생이 어디에 지원·합격했는지"를 상담자료로 제공.',
    method: [
      "백분위 = (1 + 나보다 좋은 사람 수) / N × 100, 코호트별 산출 후 병합",
      "내신은 단위수 가중평균 GPA로 전 학기 누적 산출",
    ],
    tags: ["Excel VBA"],
    updated: "2026.07.09",
  },
  {
    id: "saenggibu-review",
    title: "생기부 평가 웹앱",
    category: "대입 · 진학지도",
    status: "in-progress",
    visibility: "private",
    purpose: "연수용으로 준비된 생활기록부를 참가 교사들이 각자 평가하고 의견을 실시간으로 공유하는 웹앱.",
    method: [
      "원본 문서는 서버에 올라가지 않으며, 로컬에서 개인정보 마스킹·검수를 마친 데이터만 업로드",
      "연수 코드 + 이름으로 입장하는 경량 인증",
    ],
    tags: ["Python", "Next.js", "Supabase"],
    updated: "2026.07.25",
  },
  {
    id: "suhaeng-seteuk",
    title: "세특 작성 보조 도구",
    category: "대입 · 진학지도",
    status: "done",
    visibility: "private",
    purpose: "수행평가 제출물을 근거로 세부능력 및 특기사항의 객관적 기록 부분 작성을 보조. 총평 등 교사 고유 판단 영역은 명확히 제외하고 역할 경계를 지키도록 설계.",
    method: "제출물 텍스트를 분석해 정해진 규칙 안에서 사실 기반 초안을 생성.",
    tags: ["Python"],
    updated: "2026.07.27",
  },
  {
    id: "2028-subject-guide",
    title: "2028 학과별 권장과목 찾기",
    category: "대입 · 진학지도",
    status: "in-progress",
    visibility: "public",
    purpose: "2028학년도 대입 체제에서 학과별 권장 선택과목을 학생이 쉽게 찾아볼 수 있도록 정리한 웹 도구(대교협 자료 2차 가공).",
    method: "단일 HTML 페이지로 제작해 별도 서버 없이 정적 배포.",
    tags: ["HTML/JS"],
    repo: "https://github.com/taeyun200/2028-subject-guide",
    updated: "2026.06.25",
  },
  {
    id: "ocg-dashboard",
    title: "학교현황 대시보드",
    category: "학교 업무 자동화",
    status: "in-progress",
    visibility: "private",
    purpose: "매주 구글시트로 공유되던 주간업무계획·부서공지·학사일정을 시트를 열지 않고도 바로 확인·입력할 수 있는 교직원용 상시 대시보드.",
    method: [
      "PWA로 배포해 설치 파일 없이 브라우저에서 바로 설치",
      "벤토 레이아웃으로 일정·공지·할일 등 패널을 드래그로 재배치",
      "행사 참여 학생 명단을 캡처 이미지에서 AI 비전으로 자동 인식",
      "Google Apps Script 백엔드로 구글시트와 연동",
    ],
    tags: ["JavaScript", "PWA", "Google Apps Script", "Gemini API"],
    updated: "2026.07.29",
  },
  {
    id: "timetable-to-notion",
    title: "시간표/급식 Notion 자동 동기화",
    category: "학교 업무 자동화",
    status: "in-progress",
    visibility: "private",
    purpose: "나이스(NEIS) 시간표·급식 정보를 매일 자동으로 Notion DB에 동기화해 수동 입력 없이 최신 정보를 유지.",
    method: "GitHub Actions 스케줄러가 매일 NEIS 오픈API를 조회해 Notion API로 갱신.",
    tags: ["Python", "GitHub Actions", "NEIS API", "Notion API"],
    updated: "2026.06.17",
  },
  {
    id: "notiontoprices",
    title: "notiontoprices",
    category: "개인 생산성 자동화",
    status: "in-progress",
    visibility: "public",
    purpose: "Notion 투자일지 DB의 현재가를 장중 30분마다 자동 갱신해, 평가금액·손익을 수동 입력 없이 최신 상태로 유지.",
    method: "GitHub Actions 스케줄 실행 → 한국투자증권(KIS) 오픈API·업비트 API로 시세 조회 → Notion API로 현재가 속성만 갱신(나머지는 Notion 수식이 재계산). 파싱 로직은 별도 테스트로 검증.",
    tags: ["Python", "GitHub Actions", "Notion API"],
    repo: "https://github.com/taeyun200/notiontoprices",
    updated: "2026.07.16",
  },
  {
    id: "snapnotion",
    title: "SnapNotion",
    category: "개인 생산성 자동화",
    status: "in-progress",
    visibility: "private",
    purpose: "공문·메시지로 오는 일정·행사 정보를 화면 캡처만으로 Notion DB에 자동 등록하는 Windows용 플로팅/트레이 앱.",
    method: [
      "화면 영역을 드래그로 캡처",
      "선택한 AI(Claude/OpenAI/Gemini)가 제목·날짜·시간·장소·요약을 추출",
      "추출 결과로 Notion 페이지를 자동 생성",
    ],
    tags: ["Python", "Notion API", "Claude/OpenAI/Gemini API"],
    updated: "2026.06.20",
  },
];
